/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhereIrsLettersComeFromRouteImport } from './routes/where-irs-letters-come-from'
import { Route as IrsNoticeTimelineRouteImport } from './routes/irs-notice-timeline'
import { Route as IndexRouteImport } from './routes/index'

const WhereIrsLettersComeFromRoute = WhereIrsLettersComeFromRouteImport.update({
  id: '/where-irs-letters-come-from',
  path: '/where-irs-letters-come-from',
  getParentRoute: () => rootRouteImport,
} as any)
const IrsNoticeTimelineRoute = IrsNoticeTimelineRouteImport.update({
  id: '/irs-notice-timeline',
  path: '/irs-notice-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/irs-notice-timeline': typeof IrsNoticeTimelineRoute
  '/where-irs-letters-come-from': typeof WhereIrsLettersComeFromRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/irs-notice-timeline': typeof IrsNoticeTimelineRoute
  '/where-irs-letters-come-from': typeof WhereIrsLettersComeFromRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/irs-notice-timeline': typeof IrsNoticeTimelineRoute
  '/where-irs-letters-come-from': typeof WhereIrsLettersComeFromRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/irs-notice-timeline' | '/where-irs-letters-come-from'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/irs-notice-timeline' | '/where-irs-letters-come-from'
  id: '__root__' | '/' | '/irs-notice-timeline' | '/where-irs-letters-come-from'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IrsNoticeTimelineRoute: typeof IrsNoticeTimelineRoute
  WhereIrsLettersComeFromRoute: typeof WhereIrsLettersComeFromRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/where-irs-letters-come-from': {
      id: '/where-irs-letters-come-from'
      path: '/where-irs-letters-come-from'
      fullPath: '/where-irs-letters-come-from'
      preLoaderRoute: typeof WhereIrsLettersComeFromRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irs-notice-timeline': {
      id: '/irs-notice-timeline'
      path: '/irs-notice-timeline'
      fullPath: '/irs-notice-timeline'
      preLoaderRoute: typeof IrsNoticeTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IrsNoticeTimelineRoute: IrsNoticeTimelineRoute,
  WhereIrsLettersComeFromRoute: WhereIrsLettersComeFromRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
